### ISSUE TITLE
DeHackEd patches should be loaded by -deh instead of -file

### ISSUE THREAD

**Issue by Youda008** [Youda008/DoomRunner#7]
DeHackEd patches (files with extension .deh) should be loaded by command line option `-deh` instead of `-file`. Distinguish the case by the filename extension and generate the correct cmd option for each.

**Comment by Youda008** [comment]
Fixed in 1.1.

**Comment by DanilaSpevak** [comment]
Still getting this on 1.32
![image](https://user-images.githubusercontent.com/42034406/97835617-619dcd00-1cfc-11eb-9a41-63fb1e715a04.png)

Same when adding deh via Mods. Also tried to lowercase file extension (.deh instead of DEH) - no effect.

**Comment by Youda008** [comment]
Aaahh, fucking case sensitivity. Currently it works only if it's lower case and if it's in mod list. I will fix it to recognize all letter cases and add the check for maps too.
